name: Manual Update Checker
on:
  workflow_dispatch:

jobs:
  update-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip jq git python3
          sudo apt-get install -y libnet-ssleay-perl libio-socket-ssl-perl sendemail
          

      - name: Clone private repository
        run: |
          git clone https://${{ secrets.GH_USER }}:${{ secrets.ACCESS_TOKEN }}@github.com/opace3pro/kernel_oneplus_sm8650
          cd kernel_oneplus_sm8650
          git config user.email "${{ secrets.GH_EMAIL }}"
          git config user.name "${{ secrets.GH_USER }}"
          git remote remove origin
          git remote add origin https://github.com/crdroidandroid/android_kernel_oneplus_sm8650.git
          git branch -M 15.0
          git push -u origin 15.0
